import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Sans} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const instrumentSans = ({
  variable: "--font-instrument-sans",
  subsets: ["latin"]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${instrumentSans.variable} antialiased bg-black`}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
